<?php
namespace App\Http\Controllers;
use App\Services\ProfileService;
use App\Services\TalesDatabase;
use App\Services\TmpayService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use Throwable;
class TopUpController extends Controller {
 public function __construct(private ProfileService $profiles,private TmpayService $tmpay,private TalesDatabase $db){}
 public function index(Request $r): View { abort_unless(config('talesrunner.features.topup'),404); $profile=$this->profiles->profile($r); $history=DB::connection('web')->table('LogTopup')->where('Account_ID',$profile['id'])->orderByDesc('DateTime')->limit(50)->get(); return view('topup.index',compact('profile','history')); }
 public function submit(Request $r): RedirectResponse { abort_unless(config('talesrunner.features.topup'),404); $code=$r->validate(['code'=>['required','regex:/^[0-9]{14}$/']])['code']; $p=$this->profiles->profile($r); $q=DB::connection('web')->table('LogTopup'); if((clone $q)->where('Password',$code)->whereIn('Status',[0,1])->exists()) throw ValidationException::withMessages(['code'=>'This prepaid-card code has already been used.']); if((clone $q)->where('Account_ID',$p['id'])->where('Status',0)->count()>=3) throw ValidationException::withMessages(['code'=>'You already have three cards pending verification.']); if((clone $q)->where('Account_ID',$p['id'])->where('Status','>',1)->where('DateTime','>',now()->subDay())->count()>=3) throw ValidationException::withMessages(['code'=>'Too many failed top-up attempts. Please try again later.']); DB::connection('web')->table('LogTopup')->insert(['Password'=>$code,'Account_ID'=>$p['id'],'Amount'=>0,'Status'=>0,'DateTime'=>now()]); try{$this->tmpay->sendCard($p['id'],$code);}catch(Throwable $e){ DB::connection('web')->table('LogTopup')->where('Password',$code)->where('Account_ID',$p['id'])->where('Status',0)->delete(); throw ValidationException::withMessages(['code'=>$e->getMessage()]); } return back()->with('success','Prepaid-card information was submitted for verification.'); }
 public function callback(Request $r){ if($r->ip()!==config('talesrunner.tmpay.access_ip')) return response('ERROR|ACCESS_DENIED',403); $amountIndex=(int)$r->query('amount',-1); $code=(string)$r->query('password',''); $status=(int)$r->query('status',-1); $hash=(string)$r->query('hash',''); $amountMap=[0=>0,1=>50,2=>90,3=>150,4=>300,5=>500,6=>1000]; if(!array_key_exists($amountIndex,$amountMap)||!preg_match('/^[0-9]{14}$/',$code)||$status<0||!hash_equals(md5($code.$code),$hash)) return response('ERROR|INVALID_REQUEST',400); try { $uid=$this->db->transaction(function(TalesDatabase $db) use($code,$status,$amountIndex,$amountMap){ $log=$db->webTable('LogTopup')->where('Password',$code)->where('Status',0)->orderBy('Num')->lockForUpdate()->first(); if(!$log) throw new \RuntimeException('INVALID_USER_NO'); $db->webTable('LogTopup')->where('Num',$log->Num)->where('Status',0)->update(['Status'=>$status,'Amount'=>$amountIndex]); $real=$amountMap[$amountIndex]; if($real>0){$cash=(int)(config("talesrunner.topup.cash.{$real}")??0);$point=(int)(config("talesrunner.topup.point.{$real}")??0);$vip=(int)(config("talesrunner.topup.vip_exp.{$real}")??0);$db->webTable('Web_User')->where('fdUserID',$log->Account_ID)->update(['fdPoint'=>DB::raw("fdPoint+{$point}"),'fdEXP_VIP'=>DB::raw("fdEXP_VIP+{$vip}")]);$db->gameTable('UserInfoFromPublisher')->where('fdUserID',$log->Account_ID)->increment('fdCash',$cash);} return $log->Account_ID; }); return response('SUCCEED|UID='.$uid); } catch(Throwable $e){return response('ERROR|'.$e->getMessage(),500);} }
}
